name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Run frontend tests
        run: npm run test:frontend
      
      - name: Run backend tests
        if: ${{ hashFiles('controllers/*.test.js') != '' }}
        run: npm run test:backend

      - name: Skip backend tests (no test files found)
        if: ${{ hashFiles('controllers/*.test.js') == '' }}
        run: echo "No backend test files found under controllers/*.test.js — skipping backend tests."
